"""initial

Revision ID: 82add5769ff5
Revises: 9cfba5b777cd
Create Date: 2025-09-14 22:42:56.869141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82add5769ff5'
down_revision = '9cfba5b777cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
